language: node_js
node_js:
  - '0.10'
services:
  - mongodb
before_script:
  - npm run jshint
script:
  - npm run test-coveralls
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage